services:
  orchard:
    build: .
    ports:
      - "3321:3321"
    env_file:
      - .env  # This passes ALL variables from .env file
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - DOCKER_ENV=true
      # Lightning Network (container paths)
      - LIGHTNING_MACAROON=/app/certs/lightning/admin.macaroon
      - LIGHTNING_CERT=/app/certs/lightning/tls.cert
      # Taproot Assets (container paths)
      - TAPROOT_ASSETS_MACAROON=/app/certs/taproot/admin.macaroon
      - TAPROOT_ASSETS_CERT=/app/certs/taproot/tls.cert
      # Mint (container paths)
      - MINT_RPC_KEY=/app/certs/mint/rpc.key
      - MINT_RPC_CERT=/app/certs/mint/rpc.cert
      - MINT_RPC_CA=/app/certs/mint/rpc.ca
    volumes:
      # Only mount if the files exist (conditional mounting)
      - type: bind
        source: ${LIGHTNING_MACAROON}
        target: /app/certs/lightning/admin.macaroon
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${LIGHTNING_CERT}
        target: /app/certs/lightning/tls.cert
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${TAPROOT_ASSETS_MACAROON}
        target: /app/certs/taproot/admin.macaroon
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${TAPROOT_ASSETS_CERT}
        target: /app/certs/taproot/tls.cert
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_KEY}
        target: /app/certs/mint/rpc.key
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_CERT}
        target: /app/certs/mint/rpc.cert
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_CA}
        target: /app/certs/mint/rpc.ca
        read_only: true
        bind:
          create_host_path: false
    restart: unless-stopped