services:
  orchard:
    build: .
    ports:
      - "${SERVER_PORT:-3321}:${SERVER_PORT:-3321}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - DOCKER_ENV=true
      # Lightning Network (container paths)
      - LIGHTNING_MACAROON=/app/certs/lightning/orchard.macaroon
      - LIGHTNING_CERT=/app/certs/lightning/tls.cert
      - LIGHTNING_KEY=/app/certs/lightning/client.key
      - LIGHTNING_CA=/app/certs/lightning/ca.pem
      # Taproot Assets (container paths)
      - TAPROOT_ASSETS_MACAROON=/app/certs/taproot/orchard.macaroon
      - TAPROOT_ASSETS_CERT=/app/certs/taproot/tls.cert
      # Mint (container paths)
      - MINT_DATABASE_CA=/app/certs/mint/database.ca.pem
      - MINT_DATABASE_CERT=/app/certs/mint/database.cert.pem
      - MINT_DATABASE_KEY=/app/certs/mint/database.key.pem
      - MINT_RPC_KEY=/app/certs/mint/rpc.client.key
      - MINT_RPC_CERT=/app/certs/mint/rpc.client.pem
      - MINT_RPC_CA=/app/certs/mint/rpc.ca.pem
    tmpfs:
      - /app/data/tmp
    volumes:
      - type: bind
        source: ${LIGHTNING_MACAROON}
        target: /app/certs/lightning/orchard.macaroon
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${LIGHTNING_CERT}
        target: /app/certs/lightning/tls.cert
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${LIGHTNING_KEY}
        target: /app/certs/lightning/client.key
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${LIGHTNING_CA}
        target: /app/certs/lightning/ca.pem
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${TAPROOT_ASSETS_MACAROON}
        target: /app/certs/taproot/orchard.macaroon
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${TAPROOT_ASSETS_CERT}
        target: /app/certs/taproot/tls.cert
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_DATABASE_CA}
        target: /app/certs/mint/database.ca.pem
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_DATABASE_CERT}
        target: /app/certs/mint/database.cert.pem
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_DATABASE_KEY}
        target: /app/certs/mint/database.key.pem
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_KEY}
        target: /app/certs/mint/rpc.client.key
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_CERT}
        target: /app/certs/mint/rpc.client.pem
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${MINT_RPC_CA}
        target: /app/certs/mint/rpc.ca.pem
        read_only: true
        bind:
          create_host_path: false
    restart: unless-stopped