export const LIGHTNING_INFO_QUERY = `{
    lightning_info{
        alias
        best_header_timestamp
        block_hash
        block_height
        color
        commit_hash
        identity_pubkey
        num_active_channels
        num_inactive_channels
        num_peers
        num_pending_channels
        require_htlc_interceptor
        store_final_htlc_resolutions
        synced_to_chain
        version
        synced_to_graph
        testnet
        uris
        chains{
            chain
            network
        }
        features{
            bit
            is_known
            is_required
            name
        }
    }
}`;

export const LIGHTNING_BALANCE_QUERY = `{
    lightning_balance{
        balance
        custom_channel_data{
            open_channels{
                asset_id
                chan_id
                local_balance
                name
                remote_balance
            }
            pending_channels{
                asset_id
                chan_id
                local_balance
                name
                remote_balance
            }
        }
        local_balance{
            sat
            msat
        }
        pending_open_balance
        pending_open_remote_balance{
            sat
            msat
        }
        remote_balance{
            sat
            msat
        }
        unsettled_local_balance{
            sat
            msat
        }
        unsettled_remote_balance{
            sat
            msat
        }
    }
}`;

export const LIGHTNING_WALLET_QUERY = `{
    lightning_wallet{
        name
        address_type
        derivation_path
        addresses{
            address
            balance
            public_key
        }
	}
}`;