export enum AgentKey {
	GROUNDSKEEPER = 'GROUNDSKEEPER',
	ACTIVITY_MONITOR = 'ACTIVITY_MONITOR',
}

export enum AgentRunStatus {
	RUNNING = 'running',
	SUCCESS = 'success',
	ERROR = 'error',
}

export enum AgentToolRole {
	READ = 'read',
	WRITE = 'write',
}

export enum AgentToolCategory {
	BITCOIN = 'bitcoin',
	HEALTH = 'health',
	LIGHTNING = 'lightning',
	MEMORY = 'memory',
	MESSAGE = 'message',
	MINT = 'mint',
	SYSTEM = 'system',
}

export enum AgentToolName {
	GET_BITCOIN_ANALYTICS_METRICS = 'GET_BITCOIN_ANALYTICS_METRICS',
	GET_BITCOIN_BLOCKCHAIN_INFO = 'GET_BITCOIN_BLOCKCHAIN_INFO',
	GET_BITCOIN_NETWORK_INFO = 'GET_BITCOIN_NETWORK_INFO',
	GET_PORT_HEALTH = 'GET_PORT_HEALTH',
	GET_URL_HEALTH = 'GET_URL_HEALTH',
	GET_LIGHTNING_ANALYTICS_BALANCES = 'GET_LIGHTNING_ANALYTICS_BALANCES',
	GET_LIGHTNING_ANALYTICS_METRICS = 'GET_LIGHTNING_ANALYTICS_METRICS',
	GET_LIGHTNING_CHANNELS = 'GET_LIGHTNING_CHANNELS',
	GET_LIGHTNING_CLOSED_CHANNELS = 'GET_LIGHTNING_CLOSED_CHANNELS',
	GET_LIGHTNING_INFO = 'GET_LIGHTNING_INFO',
	GET_LIGHTNING_PEERS = 'GET_LIGHTNING_PEERS',
	GET_MINT_ANALYTICS = 'GET_MINT_ANALYTICS',
	GET_MINT_ANALYTICS_METRICS = 'GET_MINT_ANALYTICS_METRICS',
	GET_MINT_INFO = 'GET_MINT_INFO',
	GET_PAST_RUNS = 'GET_PAST_RUNS',
	GET_SYSTEM_METRICS = 'GET_SYSTEM_METRICS',
	SEND_MESSAGE = 'SEND_MESSAGE',
	SKIP_MESSAGE = 'SKIP_MESSAGE',
}
