export enum AgentKey {
	ACTIVITY_MONITOR = 'ACTIVITY_MONITOR',
}

export enum AgentRunStatus {
	RUNNING = 'running',
	SUCCESS = 'success',
	ERROR = 'error',
}

export enum AgentFunctionName {
	GET_BITCOIN_BLOCKCHAIN_INFO = 'GET_BITCOIN_BLOCKCHAIN_INFO',
	GET_BITCOIN_NETWORK_INFO = 'GET_BITCOIN_NETWORK_INFO',
	GET_HEALTH = 'GET_HEALTH',
	GET_LIGHTNING_ANALYTICS = 'GET_LIGHTNING_ANALYTICS',
	GET_LIGHTNING_INFO = 'GET_LIGHTNING_INFO',
	GET_MINT_ANALYTICS = 'GET_MINT_ANALYTICS',
	GET_MINT_INFO = 'GET_MINT_INFO',
}
