export enum LightningType {
	LND = 'lnd',
	CLN = 'cln',
}

export enum LightningAddressType {
	UNKOWN = 'UNKOWN',
	WITNESS_PUBKEY_HASH = 'WITNESS_PUBKEY_HASH',
	NESTED_WITNESS_PUBKEY_HASH = 'NESTED_WITNESS_PUBKEY_HASH',
	HYBRID_NESTED_WITNESS_PUBKEY_HASH = 'HYBRID_NESTED_WITNESS_PUBKEY_HASH',
	TAPROOT_PUBKEY = 'TAPROOT_PUBKEY',
}

export enum LightningRequestType {
	BOLT11_INVOICE = 'BOLT11_INVOICE',
	BOLT12_OFFER = 'BOLT12_OFFER',
	BOLT12_INVOICE = 'BOLT12_INVOICE',
	BOLT12_INVOICE_REQUEST = 'BOLT12_INVOICE_REQUEST',
	UNKNOWN = 'UNKNOWN',
}

export enum LightningChannelCloseType {
	COOPERATIVE = 'COOPERATIVE',
	LOCAL_FORCE = 'LOCAL_FORCE',
	REMOTE_FORCE = 'REMOTE_FORCE',
	BREACH = 'BREACH',
	FUNDING_CANCELED = 'FUNDING_CANCELED',
	ABANDONED = 'ABANDONED',
	UNKNOWN = 'UNKNOWN',
}

export enum LightningChannelOpenInitiator {
	LOCAL = 'LOCAL',
	REMOTE = 'REMOTE',
	BOTH = 'BOTH',
	UNKNOWN = 'UNKNOWN',
}
