export enum AiAgent {
    DEFAULT = 'DEFAULT',
    MINT_INFO = 'MINT_INFO',
}

export enum AiMessageRole {
    USER = 'user',
    ASSISTANT = 'assistant',
    FUNCTION = 'function',
    SYSTEM = 'system',
}

export enum AiFunctionName {
    MINT_NAME_UPDATE = 'MINT_NAME_UPDATE',
    MINT_DESCRIPTION_UPDATE = 'MINT_DESCRIPTION_UPDATE',
    MINT_ICON_URL_UPDATE = 'MINT_ICON_URL_UPDATE',
    MINT_DESCRIPTION_LONG_UPDATE = 'MINT_DESCRIPTION_LONG_UPDATE',
    MINT_MOTD_UPDATE = 'MINT_MOTD_UPDATE',
    MINT_URL_ADD = 'MINT_URL_ADD',
    MINT_URL_UPDATE = 'MINT_URL_UPDATE',
    MINT_URL_REMOVE = 'MINT_URL_REMOVE',
    MINT_CONTACT_ADD = 'MINT_CONTACT_ADD',
    // MINT_CONTACT_UPDATE = 'MINT_CONTACT_UPDATE',
    // MINT_CONTACT_REMOVE = 'MINT_CONTACT_REMOVE',
}