export enum AiAgent {
    DEFAULT = 'DEFAULT',
    MINT_DASHBOARD = 'MINT_DASHBOARD',
    MINT_INFO = 'MINT_INFO',
    MINT_CONFIG = 'MINT_CONFIG',
    MINT_KEYSETS = 'MINT_KEYSETS',
    MINT_KEYSET_ROTATION = 'MINT_KEYSET_ROTATION',
}

export enum AiMessageRole {
    USER = 'user',
    ASSISTANT = 'assistant',
    FUNCTION = 'function',
    SYSTEM = 'system',
}

export enum AiFunctionName {
    MINT_ANALYTICS_DATE_RANGE_UPDATE = 'MINT_ANALYTICS_DATE_RANGE_UPDATE',
    MINT_ANALYTICS_UNITS_UPDATE = 'MINT_ANALYTICS_UNITS_UPDATE',
    MINT_ANALYTICS_INTERVAL_UPDATE = 'MINT_ANALYTICS_INTERVAL_UPDATE',
    MINT_ANALYTICS_TYPE_UPDATE = 'MINT_ANALYTICS_TYPE_UPDATE',
    MINT_NAME_UPDATE = 'MINT_NAME_UPDATE',
    MINT_DESCRIPTION_UPDATE = 'MINT_DESCRIPTION_UPDATE',
    MINT_ICON_URL_UPDATE = 'MINT_ICON_URL_UPDATE',
    MINT_DESCRIPTION_LONG_UPDATE = 'MINT_DESCRIPTION_LONG_UPDATE',
    MINT_MOTD_UPDATE = 'MINT_MOTD_UPDATE',
    MINT_URL_ADD = 'MINT_URL_ADD',
    MINT_URL_UPDATE = 'MINT_URL_UPDATE',
    MINT_URL_REMOVE = 'MINT_URL_REMOVE',
    MINT_CONTACT_ADD = 'MINT_CONTACT_ADD',
    MINT_CONTACT_UPDATE = 'MINT_CONTACT_UPDATE',
    MINT_CONTACT_REMOVE = 'MINT_CONTACT_REMOVE',
    MINT_ENABLED_UPDATE = 'MINT_ENABLED_UPDATE',
    MINT_QUOTE_TTL_UPDATE = 'MINT_QUOTE_TTL_UPDATE',
    MINT_METHOD_MIN_UPDATE = 'MINT_METHOD_MIN_UPDATE',
    MINT_METHOD_MAX_UPDATE = 'MINT_METHOD_MAX_UPDATE',
    MINT_METHOD_DESCRIPTION_UPDATE = 'MINT_METHOD_DESCRIPTION_UPDATE',
    MINT_KEYSET_STATUS_UPDATE = 'MINT_KEYSET_STATUS_UPDATE',
    MINT_KEYSET_ROTATION_UNIT_UPDATE = 'MINT_KEYSET_ROTATION_UNIT_UPDATE',
    MINT_KEYSET_ROTATION_INPUT_FEE_PPK_UPDATE = 'MINT_KEYSET_ROTATION_INPUT_FEE_PPK_UPDATE',
    MINT_KEYSET_ROTATION_MAX_ORDER_UPDATE = 'MINT_KEYSET_ROTATION_MAX_ORDER_UPDATE',
}