export enum MintAnalyticsMetric {
	mints_amount = 'mints_amount',
	mints_created = 'mints_created',
	mints_completion_time = 'mints_completion_time',
	melts_amount = 'melts_amount',
	melts_created = 'melts_created',
	melts_completion_time = 'melts_completion_time',
	swaps_amount = 'swaps_amount',
	swaps_fee = 'swaps_fee',
	issued_amount = 'issued_amount',
	redeemed_amount = 'redeemed_amount',
	fees_amount = 'fees_amount',
	keyset_issued = 'keyset_issued',
	keyset_redeemed = 'keyset_redeemed',
}
