name: Docker Image Snapshots

on:
  workflow_dispatch:
    inputs:
      push:
        description: Push images to GHCR (false = build only)
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [mintdb-sqlite, mintdb-postgres]
        include:
          - flavor: mintdb-sqlite
            image: ghcr.io/${{ github.repository }}-mintdb-sqlite
          - flavor: mintdb-postgres
            image: ghcr.io/${{ github.repository }}-mintdb-postgres
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: inputs.push == true
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: final-${{ matrix.flavor }}
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: |
            ${{ matrix.image }}:sha-${{ github.sha }}
            ${{ matrix.image }}:${{ github.ref_name }}-snapshot
          cache-from: type=gha
          cache-to: type=gha,mode=max